newActionMap( herc );
bindAction(keyboard0, make, shift, "f1", TO, IDACTION_GENERAL_COMMAND, 0.000000);
bindAction(keyboard0, make, "delete", TO, IDACTION_SHIELD_ROTATION_ADJ, 0.125000);
bindAction(keyboard0, make, "end", TO, IDACTION_SHIELD_ROTATION_ADJ, -0.125000);
bindAction(keyboard0, make, "next", TO, IDACTION_SHIELD_FOCUS_ADJ, -0.199955);
bindAction(keyboard0, make, "prior", TO, IDACTION_SHIELD_FOCUS_ADJ, 0.199955);
bindAction(keyboard0, make, "x", TO, IDACTION_ZOOM_ADJ, 2.000000);
bindAction(keyboard0, break, "z", TO, IDACTION_ZOOM_ADJ, -1.000000);
bindAction(keyboard0, make, "]", TO, IDACTION_CENTER_BODY);
bindAction(keyboard0, make, "[", TO, IDACTION_CENTER_TURRET);
bindAction(keyboard0, make, control, "x", TO, IDACTION_CAMOUFLAGE);
bindAction(keyboard0, make, "c", TO, IDACTION_CROUCH);
bindAction(keyboard0, make, "s", TO, IDACTION_SPEED, -1.000000);
bindAction(keyboard0, make, "enter", TO, IDACTION_MAP_VIEW, 0.000000);
bindAction(keyboard0, make, control, "j", TO, IDACTION_ECM_TOGGLE);
bindAction(joystick0, make, button0, TO, IDACTION_FIRE, 1.000000);
bindAction(mouse0, make, button0, TO, IDACTION_FIRE, 1.000000);
bindAction(keyboard0, make, "space", TO, IDACTION_FIRE, 1.000000);
bindAction(keyboard0, make, "w", TO, IDACTION_SPEED, 1.000000);
bindAction(keyboard0, make, "n", TO, IDACTION_NAVPOINT_NEXT);
bindAction(keyboard0, make, "comma", TO, IDACTION_NAVPOINT_SET, -1.000000);
bindAction(keyboard0, make, shift, "n", TO, IDACTION_NAVPOINT_PREV);
bindAction(keyboard0, make, "f4", TO, IDACTION_ORDER_ALL_SQUADMATES, 0.000000);
bindAction(keyboard0, make, "f1", TO, IDACTION_ORDER_SQUADMATE_1, 0.000000);
bindAction(keyboard0, make, "f2", TO, IDACTION_ORDER_SQUADMATE_2, 0.000000);
bindAction(keyboard0, make, "f3", TO, IDACTION_ORDER_SQUADMATE_3, 0.000000);
bindAction(mouse0, yaxis0, TO, IDACTION_PITCH, DeadZone, 0.500000, Scale, 0.500000);
bindAction(keyboard0, make, "numpadenter", TO, IDACTION_REACTOR);
bindAction(mouse0, xaxis0, TO, IDACTION_ROLL, Flip, Scale, 0.500000);
bindAction(keyboard0, make, "i", TO, IDACTION_SCAN_TARGET);
bindAction(keyboard0, make, "=", TO, IDACTION_WEAPON_GROUP_ADJ, 1.000000);
bindAction(keyboard0, make, "-", TO, IDACTION_WEAPON_GROUP_ADJ, -1.000000);
bindAction(keyboard0, make, control, "1", TO, IDACTION_WEAPON_SELECT, 0.000000);
bindAction(keyboard0, make, control, "2", TO, IDACTION_WEAPON_SELECT, 1.000000);
bindAction(keyboard0, make, control, "3", TO, IDACTION_WEAPON_SELECT, 2.000000);
bindAction(keyboard0, make, control, "4", TO, IDACTION_WEAPON_SELECT, 3.000000);
bindAction(keyboard0, make, control, "5", TO, IDACTION_WEAPON_SELECT, 4.000000);
bindAction(keyboard0, make, control, "6", TO, IDACTION_WEAPON_SELECT, 5.000000);
bindAction(keyboard0, make, "1", TO, IDACTION_WEAPON_GROUP_SELECT, 0.000000);
bindAction(keyboard0, make, "2", TO, IDACTION_WEAPON_GROUP_SELECT, 1.000000);
bindAction(keyboard0, make, "3", TO, IDACTION_WEAPON_GROUP_SELECT, 2.000000);
bindAction(keyboard0, make, "quote", TO, IDACTION_SET_NAME_TAG, 1.000000);
bindAction(keyboard0, make, "m", TO, IDACTION_DROP_MARKER);
bindAction(keyboard0, make, "home", TO, IDACTION_SHIELD);
bindAction(keyboard0, make, "insert", TO, IDACTION_SHIELD_TRACK);
bindAction(keyboard0, make, "backspace", TO, IDACTION_STOP);
bindAction(keyboard0, make, "t", TO, IDACTION_TARGET_CLOSEST_ENEMY, 1.000000);
bindAction(keyboard0, make, "period", TO, IDACTION_TARGET_CLOSEST_ENEMY);
bindAction(keyboard0, make, "f", TO, IDACTION_TARGET_CLOSEST_FRIENDLY);
bindAction(keyboard0, make, "y", TO, IDACTION_TARGET_ADJ_ENEMY, 1.000000);
bindAction(keyboard0, make, "g", TO, IDACTION_TARGET_ADJ_FRIENDLY, 1.000000);
bindAction(keyboard0, make, shift, "y", TO, IDACTION_TARGET_ADJ_ENEMY, -1.000000);
bindAction(keyboard0, make, shift, "g", TO, IDACTION_TARGET_ADJ_FRIENDLY, -1.000000);
bindAction(mouse0, break, button1, TO, IDACTION_TARGET_SELECTED);
bindAction(keyboard0, make, "numpad1", TO, IDACTION_TARGET_SELECTED, 1.000000);
bindAction(keyboard0, make, control, "t", TO, IDACTION_THERMAL_DIFFUSER_TOGGLE);
bindAction(keyboard0, make, "r", TO, IDACTION_SENSOR_MODE_TOGGLE);
bindAction(keyboard0, make, "numpad0", TO, IDACTION_REVERSE_THROTTLE);
bindAction(keyboard0, make, ";", TO, IDACTION_TOGGLE_NAME_TAG, 0.000000);
bindAction(keyboard0, make, shift, "r", TO, IDACTION_SENSOR_RANGE_TOGGLE);
bindAction(keyboard0, make, shift, "1", TO, IDACTION_WEAPON_GROUP_TOGGLE, 0.000000);
bindAction(keyboard0, make, shift, "2", TO, IDACTION_WEAPON_GROUP_TOGGLE, 1.000000);
bindAction(keyboard0, make, shift, "3", TO, IDACTION_WEAPON_GROUP_TOGGLE, 2.000000);
bindAction(keyboard0, make, shift, "4", TO, IDACTION_WEAPON_GROUP_TOGGLE, 3.000000);
bindAction(keyboard0, make, shift, "5", TO, IDACTION_WEAPON_GROUP_TOGGLE, 4.000000);
bindAction(keyboard0, make, shift, "6", TO, IDACTION_WEAPON_GROUP_TOGGLE, 5.000000);
bindAction(keyboard0, make, control, "b", TO, IDACTION_TURBO);
bindAction(keyboard0, make, "a", TO, IDACTION_YAW, 1.000000);
bindAction(keyboard0, make, "d", TO, IDACTION_YAW, -1.000000);
bindAction(keyboard0, make, control, "r", TO, IDACTION_USE_REACTOR_CAPACITOR);
bindAction(keyboard0, make, control, "s", TO, IDACTION_USE_SHIELD_CAPACITOR);
bindAction(keyboard0, make, "7", TO, IDACTION_USE_SPECIAL, 0.000000);
bindAction(keyboard0, make, "8", TO, IDACTION_USE_SPECIAL, 1.000000);
bindAction(keyboard0, make, "9", TO, IDACTION_USE_SPECIAL, 2.000000);
bindAction(keyboard0, make, "0", TO, IDACTION_USE_SPECIAL, 3.000000);
bindAction(keyboard0, make, "l", TO, IDACTION_WEAPON_MODE_SELECT);
bindAction(keyboard0, make, "numpad+", TO, IDACTION_WEAPON_MODE_SELECT);
bindAction(keyboard0, make, "tab", TO, IDACTION_WEAPON_MODE_SELECT);
bindAction(keyboard0, make, "numpad/", TO, IDACTION_ZOOM_ADJ, 1.000000);
bindAction(keyboard0, break, "w", TO, IDACTION_SPEED, 0.000000);
bindAction(keyboard0, break, "space", TO, IDACTION_FIRE, 0.000000);
bindAction(joystick0, break, button0, TO, IDACTION_FIRE, 0.000000);
bindAction(keyboard0, break, "s", TO, IDACTION_SPEED, 0.000000);
bindAction(keyboard0, break, "numpad/", TO, IDACTION_ZOOM_ADJ, -1.000000);
bindAction(mouse0, break, button0, TO, IDACTION_FIRE, 0.000000);
bindAction(keyboard0, break, "d", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, break, "a", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, break, "quote", TO, IDACTION_SET_NAME_TAG, 0.000000);


newActionMap( cameraOrbit );
bindAction(joystick0, yaxis0, TO, IDACTION_PITCH, Center, Square, DeadZone, 0.099977);
bindAction(joystick0, xaxis0, TO, IDACTION_YAW, Flip, Center, Square, DeadZone, 0.099977);
bindAction(joystick0, rzaxis0, TO, IDACTION_ROLL, Center, Square, DeadZone, 0.099977);
bindAction(joystick0, make, button0, TO, IDACTION_ZOOM_MODE, 1.000000);
bindAction(joystick0, break, button0, TO, IDACTION_ZOOM_MODE, 0.000000);
bindAction(joystick0, make, button1, TO, IDACTION_NEXT);
bindAction(joystick0, make, button2, TO, IDACTION_LOOK_X);
bindAction(joystick0, make, button3, TO, IDACTION_LOOK_Y);
bindAction(keyboard0, make, "left", TO, IDACTION_YAW, -0.750000);
bindAction(keyboard0, break, "left", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, make, "right", TO, IDACTION_YAW, 0.750000);
bindAction(keyboard0, break, "right", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, make, shift, "left", TO, IDACTION_YAW, -0.750000);
bindAction(keyboard0, break, shift, "left", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, make, shift, "right", TO, IDACTION_YAW, 0.750000);
bindAction(keyboard0, break, shift, "right", TO, IDACTION_YAW, 0.000000);
bindAction(keyboard0, make, "up", TO, IDACTION_PITCH, 0.500000);
bindAction(keyboard0, break, "up", TO, IDACTION_PITCH, 0.000000);
bindAction(keyboard0, make, "down", TO, IDACTION_PITCH, -0.500000);
bindAction(keyboard0, break, "down", TO, IDACTION_PITCH, 0.000000);
bindAction(keyboard0, make, "prior", TO, IDACTION_MOVE_Y, -0.500000);
bindAction(keyboard0, break, "prior", TO, IDACTION_MOVE_Y, 0.000000);
bindAction(keyboard0, make, "next", TO, IDACTION_MOVE_Y, 0.500000);
bindAction(keyboard0, break, "next", TO, IDACTION_MOVE_Y, 0.000000);
bindAction(keyboard0, make, shift, "up", TO, IDACTION_MOVE_Y, -0.500000);
bindAction(keyboard0, break, shift, "up", TO, IDACTION_MOVE_Y, 0.000000);
bindAction(keyboard0, make, shift, "down", TO, IDACTION_MOVE_Y, 0.500000);
bindAction(keyboard0, break, shift, "down", TO, IDACTION_MOVE_Y, 0.000000);
bindAction(keyboard0, make, "home", TO, IDACTION_NEXT);
bindAction(keyboard0, make, "end", TO, IDACTION_PREV);


newActionMap( gameActions );
bindAction(keyboard0, make, "space", TO, IDACTION_RESPAWN);
bindAction(keyboard0, make, alt, "r", TO, IDACTION_RESPAWN);
bindAction(keyboard0, make, control, "c", TO, IDACTION_PILOT_CAMERA);
bindAction(keyboard0, make, control, "o", TO, IDACTION_ORBIT_CAMERA);
bindAction(keyboard0, make, control, "v", TO, IDACTION_ORBIT_CAMERA);
bindAction(keyboard0, make, "f5", TO, IDACTION_TOGGLE_CHAT_DISPLAY);
bindAction(keyboard0, make, "f6", TO, IDACTION_TELL_ALL);
bindAction(keyboard0, make, "f7", TO, IDACTION_TELL_TEAM);
bindAction(keyboard0, make, "f8", TO, IDACTION_TELL_TARGET);
bindAction(keyboard0, make, control, "f1", TO, IDACTION_QUICKCHAT, 1.000000);
bindAction(keyboard0, make, control, "f2", TO, IDACTION_QUICKCHAT, 2.000000);
bindAction(keyboard0, make, control, "f3", TO, IDACTION_QUICKCHAT, 3.000000);
bindAction(keyboard0, make, control, "f4", TO, IDACTION_QUICKCHAT, 4.000000);
bindAction(keyboard0, make, control, "f5", TO, IDACTION_QUICKCHAT, 5.000000);
bindAction(keyboard0, make, control, "f6", TO, IDACTION_QUICKCHAT, 6.000000);
bindAction(keyboard0, make, control, "f7", TO, IDACTION_QUICKCHAT, 7.000000);
bindAction(keyboard0, make, control, "f8", TO, IDACTION_QUICKCHAT, 8.000000);
bindAction(keyboard0, make, control, "f9", TO, IDACTION_QUICKCHAT, 9.000000);
bindAction(keyboard0, make, control, "f10", TO, IDACTION_QUICKCHAT, 10.000000);
bindAction(keyboard0, make, control, "f11", TO, IDACTION_QUICKCHAT, 11.000000);
bindAction(keyboard0, make, control, "f12", TO, IDACTION_QUICKCHAT, 12.000000);
bindAction(keyboard0, make, "numlock", TO, IDACTION_PAUSE);
bindAction(keyboard0, make, shift, "f9", TO, IDACTION_COLLISION_DETAIL);
bindAction(keyboard0, make, shift, "f11", TO, IDACTION_OUTLINE);
bindAction(keyboard0, make, "f9", TO, IDACTION_TOGGLE_HUD_CONFIG);
bindAction(keyboard0, make, "f11", TO, IDACTION_TOGGLE_PREF_CONFIG);
bindAction(keyboard0, make, "f12", TO, IDACTION_TOGGLE_SCOREBOARD);
bindAction(keyboard0, make, "escape", TO, IDACTION_EXIT_SIM, None);
bindAction(keyboard0, make, control, "e", TO, IDACTION_EASY_CAMERA, None);
bindAction(keyboard0, make, control, "f", TO, IDACTION_FLY_CAMERA, None);


